name: Java CI with Maven

on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 6 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 15.0.0-amzn
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15.0.0
          jdkFile: ${{ github.workspace }}/.sdkman/archives/${{ steps.sdkman.outputs.file }}
      - name: Build with Maven
        run: ./mvnw -V verify
