name: Release Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
      next-version:
        description: 'Next Development version'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set git username and email
        run: |
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config --global user.name "${GH_USERNAME}"
        env:
          GH_USERNAME: ${{ github.actor }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Prepare Release
        run: ./mvnw release:prepare -Dtag=${{ github.event.inputs.tag }} -DtagNameFormat=v@{project.version} -DdevelopmentVersion=${{ github.event.inputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Packages to GitHub Packages
        run: ./mvnw release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
